# Generated by Django 5.0 on 2024-01-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chole_cleaners", "0005_blog_comment_delete_blogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutus",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="director_images/"
            ),
        ),
    ]
